controller_manager:
  ros__parameters:
    update_rate: 50
    wheel_controller:
      type: "diff_drive_controller/DiffDriveController"
      left_wheel: "left_wheel_joint"
      right_wheel: "right_wheel_joint"
      cmd_vel_timeout: 0.5
