joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    left_wheel_names: ["left_wheel_main_hinge"]
    right_wheel_names: ["right_wheel_main_hinge"]
    wheel_separation: 0.5
    wheel_radius: 0.15
    cmd_vel_timeout: 0.5
    publish_rate: 50
    velocity_rolling_window_size: 2
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 5.0
        min_acceleration: -5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 5.0
        min_acceleration: -5.0
